{
  "comments": [
    {
      "key": {
        "uuid": "5a682502_d8e1319c",
        "filename": "docs/conf.py",
        "patchSetId": 2
      },
      "lineNbr": 1,
      "author": {
        "id": 1451
      },
      "writtenOn": "2018-09-06T20:22:13Z",
      "side": 1,
      "message": "Because you\u0027re running pylint, or some other linting against this, you\u0027ll need to add some rules/exceptions here in order for this to work.",
      "range": {
        "startLine": 1,
        "startChar": 0,
        "endLine": 1,
        "endChar": 28
      },
      "revId": "3252d6f1e7ed30b52305521da06be64b51796e28",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}